export const urlImage = "https://image.tmdb.org/t/p/w500";
export const countPageSwitch = 10;
export const popularBescending = 'Популярные по убыванию фильмы'
export const popularAscending = 'Популярные по возрастанию';
export const descendingRanking = 'Рейтинг по убыванию';
export const ascendingRating = 'Рейтинг по возрастанию';
export const defaultYear = '2020'
export const filterYear = 'filter_by_year'
export const filterSort = 'filter_by_sort'
export const filterGenres = 'filter_by_genres'
export const loginConst = 'test'
export const passwordConst = '123'
export const nextPage = 'changePage'
export const prevPage = 'prevPage'
export const sortByFavotire = 'Избранное'
export const bookmarkMovie = 'Закладки'
export const exit = "exit";
export const login = "login";
export const offPopup = "off";
export const onPopup = "on";
export const reset = "reset";
export const genresSearch = "filterByGenresSearch";
export const yearsSearch = "filterByYearsSearch";
export const years = [2020, 2019, 2018, 2017];
export const defaultSort = [popularBescending, popularAscending, descendingRanking, ascendingRating];
export const sortForUser =  [popularBescending, popularAscending, descendingRanking, ascendingRating, sortByFavotire, bookmarkMovie];